### ISSUE TITLE
Can't compile on Ubuntu 20.04 (with Boost 1.71)

### ISSUE THREAD

**Issue by Ingimarsson** [smileycoin/smileyCoin#28]
I got the following error when trying to compile on Ubuntu 20.04

```
make[3]: Entering directory '/home/brynjar/smileyCoin/src'
  CXX      bitcoin-cli.o
  CXX      rpcclient.o
In file included from rpcclient.cpp:8:
rpcprotocol.h: In instantiation of ‘bool SSLIOStreamDevice<Protocol>::connect(const string&, const string&) [with Protocol = boost::asio::ip::tcp; std::string = std::__cxx11::basic_string<char>]’:
rpcclient.cpp:54:119:   required from here
rpcprotocol.h:106:56: error: ‘class boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >’ has no member named ‘get_io_service’
  106 |         boost::asio::ip::tcp::resolver resolver(stream.get_io_service());
      |                                                 ~~~~~~~^~~~~~~~~~~~~~
In file included from util.h:15,
                 from rpcclient.cpp:9:
```

**Solution**

Install an older version of Boost

```
sudo apt --purge remove libboost-dev libboost-doc
sudo apt install libboost1.67-all-dev
```

**Comment by antonva** [comment]
#32 should have fixed this.
