### ISSUE TITLE
Can't compile on MacOS 10.15.4 with boost 1.73

### ISSUE THREAD

**Issue by Bragiar** [smileycoin/smileyCoin#50]
I get the error:

```bash
In file included from ./chainparams.h:11:
./util.h:265:53: warning: unknown escape sequence '\/' [-Wunknown-escape-sequence]
    std::string date = "([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/[0-9]{4}(([01]{0,1}[0-9])|(2[0-4])):[0-5][0-9]";
                                                    ^~
./util.h:265:77: warning: unknown escape sequence '\/' [-Wunknown-escape-sequence]
    std::string date = "([1-9]|([012][0-9])|(3[01]))\/([0]{0,1}[1-9]|1[012])\/[0-9]{4}(([01]{0,1}[0-9])|(2[0-4])):[0-5][0-9]";
                                                                            ^~
./util.h:278:30: warning: missing field 'tm_min' initializer [-Wmissing-field-initializers]
    struct tm whenTicket = {0};
                             ^
qt/bitcoingui.cpp:1048:86: error: use of undeclared identifier '_1'; did you mean 'boost::placeholders::_1'?
    uiInterface.ThreadSafeMessageBox.connect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                     ^~
                                                                                     boost::placeholders::_1
/usr/local/include/boost/bind/placeholders.hpp:46:38: note: 'boost::placeholders::_1' declared here
BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
                                     ^
qt/bitcoingui.cpp:1048:90: error: use of undeclared identifier '_2'; did you mean 'boost::placeholders::_2'?
    uiInterface.ThreadSafeMessageBox.connect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                         ^~
                                                                                         boost::placeholders::_2
/usr/local/include/boost/bind/placeholders.hpp:47:38: note: 'boost::placeholders::_2' declared here
BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
                                     ^
qt/bitcoingui.cpp:1048:94: error: use of undeclared identifier '_3'
    uiInterface.ThreadSafeMessageBox.connect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                             ^
qt/bitcoingui.cpp:1054:89: error: use of undeclared identifier '_1'; did you mean 'boost::placeholders::_1'?
    uiInterface.ThreadSafeMessageBox.disconnect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                        ^~
                                                                                        boost::placeholders::_1
/usr/local/include/boost/bind/placeholders.hpp:46:38: note: 'boost::placeholders::_1' declared here
BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
                                     ^
qt/bitcoingui.cpp:1054:93: error: use of undeclared identifier '_2'; did you mean 'boost::placeholders::_2'?
    uiInterface.ThreadSafeMessageBox.disconnect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                            ^~
                                                                                            boost::placeholders::_2
/usr/local/include/boost/bind/placeholders.hpp:47:38: note: 'boost::placeholders::_2' declared here
BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
                                     ^
qt/bitcoingui.cpp:1054:97: error: use of undeclared identifier '_3'
    uiInterface.ThreadSafeMessageBox.disconnect(boost::bind(ThreadSafeMessageBox, this, _1, _2, _3));
                                                                                                ^
In file included from qt/bitcoingui.cpp:19:
```

As the bind function got updated in boost 1.73

**Comment by gstefans** [comment]
should be solved now
